package br.com.oficina.ordemservico.domain.model;

public enum StatusOrdemDeServico {
    OS_ABERTA,
    DIAGNOSTICO_EM_ANDAMENTO,
    DIAGNOSTICO_CONCLUIDO,
    AGUARDANDO_ORCAMENTO,
    ORCAMENTO_GERADO,
    AGUARDANDO_APROVACAO,
    ORCAMENTO_APROVADO,
    SERVICO_EM_ANDAMENTO,
    AGUARDANDO_PECA,
    SERVICO_CONCLUIDO,
    OS_FINALIZADA,
    ENTREGUE
}
